<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXoliz3a\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXoliz3a/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXoliz3a.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXoliz3a\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXoliz3a\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xoliz3a',
    'container.build_id' => 'd522a838',
    'container.build_time' => 1610981298,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXoliz3a');
